### ISSUE TITLE
[Bug]: After upgrade from bridge 2.8.2 to 2.10.2 window.TelegramGameProxy.receiveEvent is not a function

### ISSUE THREAD

**Issue by kimdanielarthur-cowlabs** [Telegram-Mini-Apps/telegram-apps#758]
### Telegram Application

Telegram for Desktop and ios (not tested on android)

### Describe the Bug

Hi and thanks for a great and well maintained library!

Having just upgraded from:
"@telegram-apps/bridge": "2.8.2",
"@telegram-apps/init-data-node": "2.0.7",
"@telegram-apps/sdk": "3.10.0",

to:
"@telegram-apps/bridge": "2.10.2",
"@telegram-apps/init-data-node": "2.0.10",
"@telegram-apps/sdk": "3.11.3",.

I now see error
window.TelegramGameProxy.receiveEvent is not a function.

It also seems that any events posted are not forwarded to telegram sdk

If i check window.TelegramGameProxy i see it is defined as an empty object {}

Could it be related to the changes which now allow including telegram SDK seperately? I see there was some change in code related to populating the window.TelegramGameProxy.

I will invenstigate a bit more later and provide update if i can, have to remain on working version for now as we are pushing for some other features to release in our app.

### To Reproduce

1. Update to latest sdk versions
2. init()
3. see errors logged

### Expected Behavior

expect receiveEvent to function as before

**Comment by heyqbnk** [comment]
Could you double-check the problem on Telegram Desktop? Because I remember the issue related to the iOS client and we can't really do much there, but there should be any problems on the desktop version. 

Here is the issue:
https://github.com/Telegram-Mini-Apps/telegram-apps/issues/664

In case you are a macOS user, also check if you are using Telegram Desktop, but not Telegram for macOS - these are 2 different clients

**Comment by kimdanielarthur-cowlabs** [comment]
Happens on desktop yes, on macos (unsure what client as i can test more later when at mac)

Bear in mind this is new behaviour after an upgrade, not an ongoing issue. I've been using same clients for more than 6months without this issue.

Also not that postEvent did not seem to work either.

I can check and get some more details either in the evening or over weekend

**Comment by kimdanielarthur-cowlabs** [comment]
I tested sequenttially the updates and the error started occuring in the transition from
"@telegram-apps/sdk": "3.11.0" 
"@telegram-apps/bridge": "2.9.0",
to
"@telegram-apps/sdk": "3.11.1",
"@telegram-apps/bridge": "2.10.0",

this commit could be related
https://github.com/Telegram-Mini-Apps/telegram-apps/commit/041bd2a42317df4e6af62fb2d65db661ced746fb

I have logged out the value of window.TelegramGameProxy on the line before and after init() and its `undefined` before, but different after init() between the versions

before upgrade is `Object receiveEvent: function(e, t)`
after upgrade obejct is empty without receiveEvent Function `{}`

I see also (ios, desktop,android) suddenly things that previously were available are no longer available like:
viewport.requestFullscreen.isAvailable()
and calling function
viewport.requestFullscreen() causes error

so it seems something fishy is going on. I have not got local setup to build the telegram-apps project to debug much further. But unless you see anything obvious here i can try

**Comment by heyqbnk** [comment]
I've rolled out an update, could you check if it solves the problem? It seems like the bundler removed the code related defining properties required for apps communication.

**Comment by kimdanielarthur-cowlabs** [comment]
Yes sir, that works now nice one!
